from selenium.webdriver.common.by import By
import random

class ProjectLocators:
    index_of_item_title = random.randint(1,18)
    catalog_item_title = (By.XPATH, f'(//a[@class="categories-nav__link"])[{index_of_item_title}]')
    catalog_link_list = (By.XPATH, '//a[@class="catalog-list__link"]')
    btn_up = (By.XPATH, '//div[@class="up-button up-button_show"]')
    call_us_btn = (By.XPATH, '//div[@class="wca-body pos-left round-btn link-style-2 link-radius-1 wca-widget-loaded"]')
    call_us_window = (By.XPATH, '')
    telegram_btn = (By.XPATH, '(//a[@class="image-box"])[5]')
    whatsapp_btn = (By.XPATH, '(//a[@class="image-box"])[4]')
    vk_btn = (By.XPATH, '(//a[@class="image-box"])[7]')
    rutube_btn = (By.XPATH, '(//a[@class="image-box"])[10]')
    catalog_window = (By.XPATH, '//ul[@class="categories-nav__list"]')
    catalog_btn = (By.XPATH, '//span[@class="button header-middle-bar-shop-catalog-button catalog-dropdown-button"]')
    item_title = (By.XPATH, '//h1[@class="block__header block__header_text category-name"]')
    enter_login_window = (By.XPATH, '//div[@class="modal modal_opened"]')
    login_btn = (By.XPATH, '//a[@class="link-box link-box_style_alt-gray login-link"]')
    username_input = (By.XPATH, '//input[@title="Логин"]')
    password_input = (By.XPATH, '//input[@name="password"]')
    submit_btn = (By.XPATH, '//input[@type="submit" and @value="Войти"]')
    my_profile_link = (By.XPATH, '//a[@href="/my/profile/" and @class="contact link-box link-box_style_hover contact_size_xs"]')
    username_in_profile = (By.XPATH, '//div[@class="value__value-text"]')
    user_lastname_in_profile = (By.XPATH, '//div[@class="value value_fixed my-profile__field my-profile__field_lastname"]')
    phone_number = (By.XPATH, '//a[@class="inline" and text() ="+7 (919) 793-46-23"]')
    email = (By.XPATH, '//a[@class="inline" and text() ="shmalkopress@gmail.com"]')
    alert = (By.XPATH, '//em[@class="wa-error-msg error error_text"]')
    search_bar = (By.XPATH, '//input[@placeholder="Поиск товаров" and @name="query"]')
    search_btn = (By.XPATH, '//button[@class="input-search__button button"]')
    search_select = (By.XPATH, '(//a[@class="product-thumb__name link link_style_hover"])[1]')
    quantity_to_cart = (By.XPATH, '//input[@class="quantity__field quantity__field_active quantity__input input-text"]')
    add_to_cart = (By.XPATH, '//button[@class="product-add-to-cart__button add-to-cart button button_size_l button_fill"]')
    go_to_cart = (By.XPATH, '//a[@class="button button_size_l cart-item-modal__button"]')
    remove_from_cart = (By.XPATH, '//span[@class="wa-tooltip is-inline bottom"]')
    remove_from_cart_btn = (By.XPATH, '//button[@class="wa-button gray js-confirm button"]')
    product_added_to_cart_message = (By.XPATH, '//div[@class="modal__title"]')
    the_cart_is_empty_message = (By.XPATH, '//div[@class="not-found-block__header"]')
    quantity_value_in_cart = (By.XPATH, '//input[@class="wa-field js-product-quantity "]')
    total_price = (By.XPATH, '//span[@class="wa-price"]')
    product_name_in_cart = (By.XPATH, '//a[@class="wa-name link link_style_hover"]')
    product_price = (By.XPATH, '//div[@class="wa-product-fractional-prices"]')